version: '3.7'

services:
  tracker:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      ./.env.docker
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    volumes:
      - db_data:/var/lib/postgres_data
    environment:
      - POSTGRES_USER=tracker
      - POSTGRES_PASSWORD=deadbeef
      - POSTGRES_DB=donations

volumes:
  db_data:
